name: Verificação Diária de Medicamentos

on:
  schedule:
    # 09:00 UTC = 06:00 do Horário de Brasília (BRT)
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  verificar:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar Dependências
        run: pip install pandas

      - name: Executar Script
        env:
          SENDER_EMAIL: ${{ secrets.EMAIL_USER }}
          SENDER_ID: ${{ secrets.EMAIL_PASS }}
        run: python verificar_estoque.py
